import React from "react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='p-5'>
          <div>
            <h2>Mobiles</h2>
            <div className='py-4'>
              <div className='w-64 flex flex-col items-center justify-center'>
                <div className='rounded-xl bg-blue-100 p-5'>
                  <Image
                    className='object-contain'
                    src='/products/iphone.png'
                    width={200}
                    height={300}
                    alt='iphone'
                  />
                </div>
                <div className='mt-2'>
                  <h3 className='font-bold text-lg'>Iphone 14</h3>
                </div>
                <p className='text-sm mt-2'>
                  Excepteur cupidatat voluptate ipsum non deserunt exercitation
                  duis cillum amet adipisicing aliqua.
                </p>
                <div className='my-2 border rounded-lg border-emerald-300'>
                  <button className='p-2'>Add to cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
